api_platform:
    defaults:
        pagination_enabled: false
    eager_loading:
#      max_joins: 300 # only workaround to check the relation problems, has to be removed later!
      force_eager: false # deactivated now because i got to many join exception in trainingPlanExercise loading

    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: ['text/html']
        multipart: ['multipart/form-data']
        jsonhal:  ['application/hal+json']
        jsonapi:  ['application/vnd.api+json']
        xml:      ['application/xml', 'text/xml']
        yaml:     ['application/x-yaml']
        csv:      ['text/csv']
#        myformat: ['application/vnd.myformat']

    patch_formats:
        jsonld:   ['application/ld+json']
        jsonhal:  ['application/hal+json']
        jsonapi:  ['application/vnd.api+json']
        json:     ['application/json']
        xml:      ['application/xml', 'text/xml']
        yaml:     ['application/x-yaml']
        csv:      ['text/csv']
        html:     ['text/html']
#        json: ['application/merge-patch+json']
