<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220326213130 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE refresh_tokens (id INT AUTO_INCREMENT NOT NULL, refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid DATETIME NOT NULL, UNIQUE INDEX UNIQ_9BACE7E1C74F2195 (refresh_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE dashboard_x_widget CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE dashboard_x_widget ADD CONSTRAINT FK_BE5FCBC6BC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE dashboard_x_widget ADD CONSTRAINT FK_BE5FCBC65C94FFF8 FOREIGN KEY (dashboard) REFERENCES dashboards (id)');
        $this->addSql('ALTER TABLE dashboard_x_widget ADD CONSTRAINT FK_BE5FCBC6324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE dashboard_x_widget ADD CONSTRAINT FK_BE5FCBC685F91ED0 FOREIGN KEY (widget) REFERENCES widgets (id)');
        $this->addSql('ALTER TABLE dashboards CHANGE user user CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE dashboards ADD CONSTRAINT FK_A83421DABC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE dashboards ADD CONSTRAINT FK_A83421DA324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE dashboards ADD CONSTRAINT FK_A83421DA8D93D649 FOREIGN KEY (user) REFERENCES users (id)');
        $this->addSql('ALTER TABLE device_groups CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE device_groups ADD CONSTRAINT FK_237D486BBC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE device_groups ADD CONSTRAINT FK_237D486B324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE device_options CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE device_options ADD CONSTRAINT FK_5A83231ABC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE device_options ADD CONSTRAINT FK_5A83231A324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE device_x_device_group CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE device_x_device_group ADD CONSTRAINT FK_50AAA5CDBC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE device_x_device_group ADD CONSTRAINT FK_50AAA5CD92FB68E FOREIGN KEY (device) REFERENCES devices (id)');
        $this->addSql('ALTER TABLE device_x_device_group ADD CONSTRAINT FK_50AAA5CDAB45A4A2 FOREIGN KEY (device_group) REFERENCES device_groups (id)');
        $this->addSql('ALTER TABLE device_x_device_group ADD CONSTRAINT FK_50AAA5CD324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE device_x_device_option CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE device_x_device_option ADD CONSTRAINT FK_5460E263BC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE device_x_device_option ADD CONSTRAINT FK_5460E26392FB68E FOREIGN KEY (device) REFERENCES devices (id)');
        $this->addSql('ALTER TABLE device_x_device_option ADD CONSTRAINT FK_5460E263899671AB FOREIGN KEY (device_option) REFERENCES device_options (id)');
        $this->addSql('ALTER TABLE device_x_device_option ADD CONSTRAINT FK_5460E263324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE devices CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE devices ADD CONSTRAINT FK_11074E9ABC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE devices ADD CONSTRAINT FK_11074E9A324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE exercise_options CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_options ADD CONSTRAINT FK_A200DC2BC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE exercise_options ADD CONSTRAINT FK_A200DC2324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE exercise_types CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_types ADD CONSTRAINT FK_7C067EF2BC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE exercise_types ADD CONSTRAINT FK_7C067EF2324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE exercise_x_device CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_x_device ADD CONSTRAINT FK_718B7BD7BC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE exercise_x_device ADD CONSTRAINT FK_718B7BD792FB68E FOREIGN KEY (device) REFERENCES devices (id)');
        $this->addSql('ALTER TABLE exercise_x_device ADD CONSTRAINT FK_718B7BD7AEDAD51C FOREIGN KEY (exercise) REFERENCES exercises (id)');
        $this->addSql('ALTER TABLE exercise_x_device ADD CONSTRAINT FK_718B7BD7324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE exercise_x_device_option CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_x_device_option ADD CONSTRAINT FK_B9816180BC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE exercise_x_device_option ADD CONSTRAINT FK_B98161805A8600B0 FOREIGN KEY (`option`) REFERENCES device_options (id)');
        $this->addSql('ALTER TABLE exercise_x_device_option ADD CONSTRAINT FK_B9816180AEDAD51C FOREIGN KEY (exercise) REFERENCES exercises (id)');
        $this->addSql('ALTER TABLE exercise_x_device_option ADD CONSTRAINT FK_B9816180324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_B9816180AEDAD51C ON exercise_x_device_option (exercise)');
        $this->addSql('ALTER TABLE exercise_x_exercise_option CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_x_exercise_option ADD CONSTRAINT FK_440E48C1BC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE exercise_x_exercise_option ADD CONSTRAINT FK_440E48C1AEDAD51C FOREIGN KEY (exercise) REFERENCES exercises (id)');
        $this->addSql('ALTER TABLE exercise_x_exercise_option ADD CONSTRAINT FK_440E48C12FC995DB FOREIGN KEY (exercise_option) REFERENCES exercise_options (id)');
        $this->addSql('ALTER TABLE exercise_x_exercise_option ADD CONSTRAINT FK_440E48C1324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE exercise_x_exercise_type CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_x_exercise_type ADD CONSTRAINT FK_E5EC25B0BC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE exercise_x_exercise_type ADD CONSTRAINT FK_E5EC25B0AEDAD51C FOREIGN KEY (exercise) REFERENCES exercises (id)');
        $this->addSql('ALTER TABLE exercise_x_exercise_type ADD CONSTRAINT FK_E5EC25B0D5FB359B FOREIGN KEY (exercise_type) REFERENCES exercise_types (id)');
        $this->addSql('ALTER TABLE exercise_x_exercise_type ADD CONSTRAINT FK_E5EC25B0324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE exercise_x_muscle CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_x_muscle ADD CONSTRAINT FK_8BB5D4B6BC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE exercise_x_muscle ADD CONSTRAINT FK_8BB5D4B6AEDAD51C FOREIGN KEY (exercise) REFERENCES exercises (id)');
        $this->addSql('ALTER TABLE exercise_x_muscle ADD CONSTRAINT FK_8BB5D4B6F31119EF FOREIGN KEY (muscle) REFERENCES muscles (id)');
        $this->addSql('ALTER TABLE exercise_x_muscle ADD CONSTRAINT FK_8BB5D4B6324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE exercises CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercises ADD CONSTRAINT FK_FA14991BC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE exercises ADD CONSTRAINT FK_FA14991324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE muscle_groups CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE muscle_groups ADD CONSTRAINT FK_113C5C25BC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE muscle_groups ADD CONSTRAINT FK_113C5C25324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE muscle_x_muscle_group CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE muscle_x_muscle_group ADD CONSTRAINT FK_79B152CCBC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE muscle_x_muscle_group ADD CONSTRAINT FK_79B152CCF31119EF FOREIGN KEY (muscle) REFERENCES muscles (id)');
        $this->addSql('ALTER TABLE muscle_x_muscle_group ADD CONSTRAINT FK_79B152CC323D098E FOREIGN KEY (muscle_group) REFERENCES muscle_groups (id)');
        $this->addSql('ALTER TABLE muscle_x_muscle_group ADD CONSTRAINT FK_79B152CC324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE muscles CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE muscles ADD CONSTRAINT FK_2B4821FBBC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE muscles ADD CONSTRAINT FK_2B4821FB324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE training_diaries CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE training_diaries ADD CONSTRAINT FK_E3B40035BC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE training_diaries ADD CONSTRAINT FK_E3B40035B83DAAE5 FOREIGN KEY (training_plan_x_exercise) REFERENCES exercises (id)');
        $this->addSql('ALTER TABLE training_diaries ADD CONSTRAINT FK_E3B40035324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE training_diary_x_device_option CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE training_diary_x_device_option ADD CONSTRAINT FK_C827C2DBC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE training_diary_x_device_option ADD CONSTRAINT FK_C827C2D899671AB FOREIGN KEY (device_option) REFERENCES device_options (id)');
        $this->addSql('ALTER TABLE training_diary_x_device_option ADD CONSTRAINT FK_C827C2DDE168DF7 FOREIGN KEY (training_plan_exercise) REFERENCES training_plan_x_exercise (id)');
        $this->addSql('ALTER TABLE training_diary_x_device_option ADD CONSTRAINT FK_C827C2D324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE training_diary_x_exercise_option CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE training_diary_x_exercise_option ADD CONSTRAINT FK_3CA153BFBC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE training_diary_x_exercise_option ADD CONSTRAINT FK_3CA153BF2FC995DB FOREIGN KEY (exercise_option) REFERENCES exercise_options (id)');
        $this->addSql('ALTER TABLE training_diary_x_exercise_option ADD CONSTRAINT FK_3CA153BFDE168DF7 FOREIGN KEY (training_plan_exercise) REFERENCES training_plan_x_exercise (id)');
        $this->addSql('ALTER TABLE training_diary_x_exercise_option ADD CONSTRAINT FK_3CA153BF324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE training_diary_x_training_plan_exercise CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE training_diary_x_training_plan_exercise ADD CONSTRAINT FK_8DB0DC55BC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE training_diary_x_training_plan_exercise ADD CONSTRAINT FK_8DB0DC557EA1678F FOREIGN KEY (training_diary) REFERENCES training_diaries (id)');
        $this->addSql('ALTER TABLE training_diary_x_training_plan_exercise ADD CONSTRAINT FK_8DB0DC55B83DAAE5 FOREIGN KEY (training_plan_x_exercise) REFERENCES training_plan_x_exercise (id)');
        $this->addSql('ALTER TABLE training_diary_x_training_plan_exercise ADD CONSTRAINT FK_8DB0DC55324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE training_plan_layouts CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE training_plan_layouts ADD CONSTRAINT FK_F39C1231BC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE training_plan_layouts ADD CONSTRAINT FK_F39C1231324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE training_plan_x_device_option CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE training_plan_x_device_option ADD CONSTRAINT FK_4FDB80BFBC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE training_plan_x_device_option ADD CONSTRAINT FK_4FDB80BF899671AB FOREIGN KEY (device_option) REFERENCES device_options (id)');
        $this->addSql('ALTER TABLE training_plan_x_device_option ADD CONSTRAINT FK_4FDB80BFB83DAAE5 FOREIGN KEY (training_plan_x_exercise) REFERENCES training_plan_x_exercise (id)');
        $this->addSql('ALTER TABLE training_plan_x_device_option ADD CONSTRAINT FK_4FDB80BF324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE training_plan_x_exercise CHANGE creater creater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE training_plan_x_exercise ADD CONSTRAINT FK_B83DAAE546E902E9 FOREIGN KEY (creater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE training_plan_x_exercise ADD CONSTRAINT FK_B83DAAE5AEDAD51C FOREIGN KEY (exercise) REFERENCES exercises (id)');
        $this->addSql('ALTER TABLE training_plan_x_exercise ADD CONSTRAINT FK_B83DAAE5D2C01C3E FOREIGN KEY (training_plan) REFERENCES training_plans (id)');
        $this->addSql('ALTER TABLE training_plan_x_exercise ADD CONSTRAINT FK_B83DAAE5324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_B83DAAE5AEDAD51C ON training_plan_x_exercise (exercise)');
        $this->addSql('ALTER TABLE training_plan_x_exercise_option CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE training_plan_x_exercise_option ADD CONSTRAINT FK_CBDD4649BC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE training_plan_x_exercise_option ADD CONSTRAINT FK_CBDD46492FC995DB FOREIGN KEY (exercise_option) REFERENCES exercise_options (id)');
        $this->addSql('ALTER TABLE training_plan_x_exercise_option ADD CONSTRAINT FK_CBDD4649B83DAAE5 FOREIGN KEY (training_plan_x_exercise) REFERENCES training_plan_x_exercise (id)');
        $this->addSql('ALTER TABLE training_plan_x_exercise_option ADD CONSTRAINT FK_CBDD4649324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE training_plans CHANGE user user CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE training_plans ADD CONSTRAINT FK_DABD12BCBC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE training_plans ADD CONSTRAINT FK_DABD12BC3D8E604F FOREIGN KEY (parent) REFERENCES training_plans (id)');
        $this->addSql('ALTER TABLE training_plans ADD CONSTRAINT FK_DABD12BC2A090947 FOREIGN KEY (training_plan_layout) REFERENCES training_plan_layouts (id)');
        $this->addSql('ALTER TABLE training_plans ADD CONSTRAINT FK_DABD12BC324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE training_plans ADD CONSTRAINT FK_DABD12BC8D93D649 FOREIGN KEY (user) REFERENCES users (id)');
        $this->addSql('ALTER TABLE user_state CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE user_state ADD CONSTRAINT FK_415129A3BC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE user_state ADD CONSTRAINT FK_415129A3324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE users CHANGE id id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9BC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9A393D2FB FOREIGN KEY (state) REFERENCES user_state (id)');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
        $this->addSql('ALTER TABLE widgets CHANGE creator creator CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE widgets ADD CONSTRAINT FK_9D58E4C1BC06EA63 FOREIGN KEY (creator) REFERENCES users (id)');
        $this->addSql('ALTER TABLE widgets ADD CONSTRAINT FK_9D58E4C1324F23A6 FOREIGN KEY (updater) REFERENCES users (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('ALTER TABLE dashboard_x_widget DROP FOREIGN KEY FK_BE5FCBC6BC06EA63');
        $this->addSql('ALTER TABLE dashboard_x_widget DROP FOREIGN KEY FK_BE5FCBC65C94FFF8');
        $this->addSql('ALTER TABLE dashboard_x_widget DROP FOREIGN KEY FK_BE5FCBC6324F23A6');
        $this->addSql('ALTER TABLE dashboard_x_widget DROP FOREIGN KEY FK_BE5FCBC685F91ED0');
        $this->addSql('ALTER TABLE dashboard_x_widget CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE dashboards DROP FOREIGN KEY FK_A83421DABC06EA63');
        $this->addSql('ALTER TABLE dashboards DROP FOREIGN KEY FK_A83421DA324F23A6');
        $this->addSql('ALTER TABLE dashboards DROP FOREIGN KEY FK_A83421DA8D93D649');
        $this->addSql('ALTER TABLE dashboards CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE user user CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE device_groups DROP FOREIGN KEY FK_237D486BBC06EA63');
        $this->addSql('ALTER TABLE device_groups DROP FOREIGN KEY FK_237D486B324F23A6');
        $this->addSql('ALTER TABLE device_groups CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE device_options DROP FOREIGN KEY FK_5A83231ABC06EA63');
        $this->addSql('ALTER TABLE device_options DROP FOREIGN KEY FK_5A83231A324F23A6');
        $this->addSql('ALTER TABLE device_options CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE device_x_device_group DROP FOREIGN KEY FK_50AAA5CDBC06EA63');
        $this->addSql('ALTER TABLE device_x_device_group DROP FOREIGN KEY FK_50AAA5CD92FB68E');
        $this->addSql('ALTER TABLE device_x_device_group DROP FOREIGN KEY FK_50AAA5CDAB45A4A2');
        $this->addSql('ALTER TABLE device_x_device_group DROP FOREIGN KEY FK_50AAA5CD324F23A6');
        $this->addSql('ALTER TABLE device_x_device_group CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE device_x_device_option DROP FOREIGN KEY FK_5460E263BC06EA63');
        $this->addSql('ALTER TABLE device_x_device_option DROP FOREIGN KEY FK_5460E26392FB68E');
        $this->addSql('ALTER TABLE device_x_device_option DROP FOREIGN KEY FK_5460E263899671AB');
        $this->addSql('ALTER TABLE device_x_device_option DROP FOREIGN KEY FK_5460E263324F23A6');
        $this->addSql('ALTER TABLE device_x_device_option CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE devices DROP FOREIGN KEY FK_11074E9ABC06EA63');
        $this->addSql('ALTER TABLE devices DROP FOREIGN KEY FK_11074E9A324F23A6');
        $this->addSql('ALTER TABLE devices CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_options DROP FOREIGN KEY FK_A200DC2BC06EA63');
        $this->addSql('ALTER TABLE exercise_options DROP FOREIGN KEY FK_A200DC2324F23A6');
        $this->addSql('ALTER TABLE exercise_options CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_types DROP FOREIGN KEY FK_7C067EF2BC06EA63');
        $this->addSql('ALTER TABLE exercise_types DROP FOREIGN KEY FK_7C067EF2324F23A6');
        $this->addSql('ALTER TABLE exercise_types CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_x_device DROP FOREIGN KEY FK_718B7BD7BC06EA63');
        $this->addSql('ALTER TABLE exercise_x_device DROP FOREIGN KEY FK_718B7BD792FB68E');
        $this->addSql('ALTER TABLE exercise_x_device DROP FOREIGN KEY FK_718B7BD7AEDAD51C');
        $this->addSql('ALTER TABLE exercise_x_device DROP FOREIGN KEY FK_718B7BD7324F23A6');
        $this->addSql('ALTER TABLE exercise_x_device CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_x_device_option DROP FOREIGN KEY FK_B9816180BC06EA63');
        $this->addSql('ALTER TABLE exercise_x_device_option DROP FOREIGN KEY FK_B98161805A8600B0');
        $this->addSql('ALTER TABLE exercise_x_device_option DROP FOREIGN KEY FK_B9816180AEDAD51C');
        $this->addSql('ALTER TABLE exercise_x_device_option DROP FOREIGN KEY FK_B9816180324F23A6');
        $this->addSql('DROP INDEX IDX_B9816180AEDAD51C ON exercise_x_device_option');
        $this->addSql('ALTER TABLE exercise_x_device_option CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_x_exercise_option DROP FOREIGN KEY FK_440E48C1BC06EA63');
        $this->addSql('ALTER TABLE exercise_x_exercise_option DROP FOREIGN KEY FK_440E48C1AEDAD51C');
        $this->addSql('ALTER TABLE exercise_x_exercise_option DROP FOREIGN KEY FK_440E48C12FC995DB');
        $this->addSql('ALTER TABLE exercise_x_exercise_option DROP FOREIGN KEY FK_440E48C1324F23A6');
        $this->addSql('ALTER TABLE exercise_x_exercise_option CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_x_exercise_type DROP FOREIGN KEY FK_E5EC25B0BC06EA63');
        $this->addSql('ALTER TABLE exercise_x_exercise_type DROP FOREIGN KEY FK_E5EC25B0AEDAD51C');
        $this->addSql('ALTER TABLE exercise_x_exercise_type DROP FOREIGN KEY FK_E5EC25B0D5FB359B');
        $this->addSql('ALTER TABLE exercise_x_exercise_type DROP FOREIGN KEY FK_E5EC25B0324F23A6');
        $this->addSql('ALTER TABLE exercise_x_exercise_type CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercise_x_muscle DROP FOREIGN KEY FK_8BB5D4B6BC06EA63');
        $this->addSql('ALTER TABLE exercise_x_muscle DROP FOREIGN KEY FK_8BB5D4B6AEDAD51C');
        $this->addSql('ALTER TABLE exercise_x_muscle DROP FOREIGN KEY FK_8BB5D4B6F31119EF');
        $this->addSql('ALTER TABLE exercise_x_muscle DROP FOREIGN KEY FK_8BB5D4B6324F23A6');
        $this->addSql('ALTER TABLE exercise_x_muscle CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE exercises DROP FOREIGN KEY FK_FA14991BC06EA63');
        $this->addSql('ALTER TABLE exercises DROP FOREIGN KEY FK_FA14991324F23A6');
        $this->addSql('ALTER TABLE exercises CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE muscle_groups DROP FOREIGN KEY FK_113C5C25BC06EA63');
        $this->addSql('ALTER TABLE muscle_groups DROP FOREIGN KEY FK_113C5C25324F23A6');
        $this->addSql('ALTER TABLE muscle_groups CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE muscle_x_muscle_group DROP FOREIGN KEY FK_79B152CCBC06EA63');
        $this->addSql('ALTER TABLE muscle_x_muscle_group DROP FOREIGN KEY FK_79B152CCF31119EF');
        $this->addSql('ALTER TABLE muscle_x_muscle_group DROP FOREIGN KEY FK_79B152CC323D098E');
        $this->addSql('ALTER TABLE muscle_x_muscle_group DROP FOREIGN KEY FK_79B152CC324F23A6');
        $this->addSql('ALTER TABLE muscle_x_muscle_group CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE muscles DROP FOREIGN KEY FK_2B4821FBBC06EA63');
        $this->addSql('ALTER TABLE muscles DROP FOREIGN KEY FK_2B4821FB324F23A6');
        $this->addSql('ALTER TABLE muscles CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE training_diaries DROP FOREIGN KEY FK_E3B40035BC06EA63');
        $this->addSql('ALTER TABLE training_diaries DROP FOREIGN KEY FK_E3B40035B83DAAE5');
        $this->addSql('ALTER TABLE training_diaries DROP FOREIGN KEY FK_E3B40035324F23A6');
        $this->addSql('ALTER TABLE training_diaries CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE training_diary_x_device_option DROP FOREIGN KEY FK_C827C2DBC06EA63');
        $this->addSql('ALTER TABLE training_diary_x_device_option DROP FOREIGN KEY FK_C827C2D899671AB');
        $this->addSql('ALTER TABLE training_diary_x_device_option DROP FOREIGN KEY FK_C827C2DDE168DF7');
        $this->addSql('ALTER TABLE training_diary_x_device_option DROP FOREIGN KEY FK_C827C2D324F23A6');
        $this->addSql('ALTER TABLE training_diary_x_device_option CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE training_diary_x_exercise_option DROP FOREIGN KEY FK_3CA153BFBC06EA63');
        $this->addSql('ALTER TABLE training_diary_x_exercise_option DROP FOREIGN KEY FK_3CA153BF2FC995DB');
        $this->addSql('ALTER TABLE training_diary_x_exercise_option DROP FOREIGN KEY FK_3CA153BFDE168DF7');
        $this->addSql('ALTER TABLE training_diary_x_exercise_option DROP FOREIGN KEY FK_3CA153BF324F23A6');
        $this->addSql('ALTER TABLE training_diary_x_exercise_option CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE training_diary_x_training_plan_exercise DROP FOREIGN KEY FK_8DB0DC55BC06EA63');
        $this->addSql('ALTER TABLE training_diary_x_training_plan_exercise DROP FOREIGN KEY FK_8DB0DC557EA1678F');
        $this->addSql('ALTER TABLE training_diary_x_training_plan_exercise DROP FOREIGN KEY FK_8DB0DC55B83DAAE5');
        $this->addSql('ALTER TABLE training_diary_x_training_plan_exercise DROP FOREIGN KEY FK_8DB0DC55324F23A6');
        $this->addSql('ALTER TABLE training_diary_x_training_plan_exercise CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE training_plan_layouts DROP FOREIGN KEY FK_F39C1231BC06EA63');
        $this->addSql('ALTER TABLE training_plan_layouts DROP FOREIGN KEY FK_F39C1231324F23A6');
        $this->addSql('ALTER TABLE training_plan_layouts CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE training_plan_x_device_option DROP FOREIGN KEY FK_4FDB80BFBC06EA63');
        $this->addSql('ALTER TABLE training_plan_x_device_option DROP FOREIGN KEY FK_4FDB80BF899671AB');
        $this->addSql('ALTER TABLE training_plan_x_device_option DROP FOREIGN KEY FK_4FDB80BFB83DAAE5');
        $this->addSql('ALTER TABLE training_plan_x_device_option DROP FOREIGN KEY FK_4FDB80BF324F23A6');
        $this->addSql('ALTER TABLE training_plan_x_device_option CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE training_plan_x_exercise DROP FOREIGN KEY FK_B83DAAE546E902E9');
        $this->addSql('ALTER TABLE training_plan_x_exercise DROP FOREIGN KEY FK_B83DAAE5AEDAD51C');
        $this->addSql('ALTER TABLE training_plan_x_exercise DROP FOREIGN KEY FK_B83DAAE5D2C01C3E');
        $this->addSql('ALTER TABLE training_plan_x_exercise DROP FOREIGN KEY FK_B83DAAE5324F23A6');
        $this->addSql('DROP INDEX IDX_B83DAAE5AEDAD51C ON training_plan_x_exercise');
        $this->addSql('ALTER TABLE training_plan_x_exercise CHANGE creater creater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE training_plan_x_exercise_option DROP FOREIGN KEY FK_CBDD4649BC06EA63');
        $this->addSql('ALTER TABLE training_plan_x_exercise_option DROP FOREIGN KEY FK_CBDD46492FC995DB');
        $this->addSql('ALTER TABLE training_plan_x_exercise_option DROP FOREIGN KEY FK_CBDD4649B83DAAE5');
        $this->addSql('ALTER TABLE training_plan_x_exercise_option DROP FOREIGN KEY FK_CBDD4649324F23A6');
        $this->addSql('ALTER TABLE training_plan_x_exercise_option CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE training_plans DROP FOREIGN KEY FK_DABD12BCBC06EA63');
        $this->addSql('ALTER TABLE training_plans DROP FOREIGN KEY FK_DABD12BC3D8E604F');
        $this->addSql('ALTER TABLE training_plans DROP FOREIGN KEY FK_DABD12BC2A090947');
        $this->addSql('ALTER TABLE training_plans DROP FOREIGN KEY FK_DABD12BC324F23A6');
        $this->addSql('ALTER TABLE training_plans DROP FOREIGN KEY FK_DABD12BC8D93D649');
        $this->addSql('ALTER TABLE training_plans CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE user user CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE user_state DROP FOREIGN KEY FK_415129A3BC06EA63');
        $this->addSql('ALTER TABLE user_state DROP FOREIGN KEY FK_415129A3324F23A6');
        $this->addSql('ALTER TABLE user_state CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E9BC06EA63');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E9A393D2FB');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E9324F23A6');
        $this->addSql('ALTER TABLE users CHANGE id id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE widgets DROP FOREIGN KEY FK_9D58E4C1BC06EA63');
        $this->addSql('ALTER TABLE widgets DROP FOREIGN KEY FK_9D58E4C1324F23A6');
        $this->addSql('ALTER TABLE widgets CHANGE creator creator CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\', CHANGE updater updater CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_0900_ai_ci` COMMENT \'(DC2Type:uuid)\'');
    }
}
