#index:
#    path: /{page}
#    requirements:
#      page: "^(?!api).*"
#    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
#    defaults:
#      template: 'template.html.twig'
#    controller: App\Controller\DefaultController::index

authentication_token:
  path: /authentication_token
  methods: ['POST']

api_login_check:
  path: /api/login_check
