parameters:
    public_directory: 'vfs://public'
    uploads_directory: '%public_directory%/uploads'
    dynamic_content_directory: '%public_directory%/images/content/dynamic'

services:
    App\Tests\ApiHelper:
        class: App\Tests\ApiHelper
        public: true
